name = "enchanted-invitation-suite"
compatibility_date = "2026-01-01"   # Use a recent date

pages_build_output_dir = "dist"     # This is supported & recommended

# Delete everything else:
# NO [build]...
# NO [site]...
# NO [env.production]...
# NO [vars] unless you have Functions/bindings